#!/usr/bin/env python3

from tempfile import mktemp
from json import dump
import sys
from sys import argv, stdin, stdout, stderr
import subprocess
from subprocess import Popen, PIPE
from os import environ

fname = mktemp()
state = dict(env={}, argv=argv[1:])
for (k, v) in environ.items():
    state['env'][k] = v

with open(fname, 'w') as f:
    dump(state, f)

p = Popen(['su', '-', 'colab', '-c', f"deroot_out {fname}"], stdin = stdin, stdout = PIPE, stderr = subprocess.STDOUT)
for c in iter(lambda: p.stdout.read(1), b""):
    sys.stdout.buffer.write(c)
p.wait()
sys.exit(p.returncode)
