#!/usr/bin/env node

const fs = require('fs')
const {spawn, spawnSync} = require("child_process");
const path = require('path');
const OS = require("os");

const tmpDir = fs.mkdtempSync(path.join(OS.tmpdir(), "deroot"))

const removeTmpDir = () => {
  spawnSync("rm", ["-rf", tmpDir])
}

process.on("exit", () => {
  removeTmpDir()
})

process.on("uncaughtException", () => {
  removeTmpDir()
})

const runArgs = process.argv.slice(2)

const processConfig = {
  env: process.env,
  args: runArgs,
}

const processConfigPath = path.join(tmpDir, "processConfig")
fs.writeFileSync(processConfigPath, JSON.stringify(processConfig))
fs.chmodSync(tmpDir, 777)
fs.chmodSync(processConfigPath, 444)

const runAsUser = process.env.DEROOT_USER ?? "colab"

const subprocess = spawn("su", ["-", runAsUser, "-c", `deroot_out ${processConfigPath}`], {
  stdio: [0, 1, 2],
})

subprocess.on("exit", (code) => {
  process.exit(code)
})

