#!/usr/bin/env bash

CURRENT_DIR=`cd "$(dirname "$0")"; pwd`

chmod 777 /content

if [[ ! -d /content/user ]]; then
    echo "Creating user..."
    useradd -m --home-dir /content/user -g users colab
    echo 'colab ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
fi

which deroot >/dev/null 2>/dev/null || {
    echo "Installing deroot wrapper script..."
    curl -L https://raw.githubusercontent.com/srounce/nix-on-colab/master/deroot > /tmp/deroot
    install -m755 "/tmp/deroot" /bin
}

which deroot_out >/dev/null 2>/dev/null || {
    echo "Installing deroot_out wrapper script..."
    curl -L https://raw.githubusercontent.com/srounce/nix-on-colab/master/deroot_out > /tmp/deroot_out
    install -m755 "/tmp/deroot_out" /bin
}

if [[ ! -d /nix ]]; then
    echo "Installing nix..."
    mkdir -m 0755 /nix && chown colab /nix
    curl -L https://nixos.org/nix/install > /tmp/nix-install
    mkdir -p /etc/nix
    echo 'sandbox = false' > /etc/nix/nix.conf
    yes y | deroot sh /tmp/nix-install # --daemon
    echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
    echo 'sandbox = false' >> /etc/nix/nix.conf
    echo 'trusted-users = colab root @wheel' >> /etc/nix/nix.conf
fi

